#!/usr/bin/env python3
"""Local web frontend for probeocr (standard library only).

    python3 frontend/server.py [--root DIR] [--port 8765] [--no-browser]

Shows every image under the root folder (default: the current directory) as a
checkable tree, lets you draw and label probe regions on a reference
screenshot, then runs the C extractor (bin/probeocr) over a whole folder and
streams the results back for review and CSV export. Binds to 127.0.0.1 only.
"""
import argparse
import json
import os
import re
import subprocess
import sys
import tempfile
import threading
import webbrowser
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import parse_qs, urlparse

ROOT = Path(__file__).resolve().parent.parent
STATIC = Path(__file__).resolve().parent / "static"


def pick_layouts_dir() -> Path:
    """<install>/layouts if we can write there, else a per-user folder.

    The app never needs admin rights; this keeps Save layout working when it is
    unpacked somewhere read-only such as C:\\Program Files.
    """
    local = ROOT / "layouts"
    try:
        local.mkdir(exist_ok=True)
        tempfile.TemporaryFile(dir=local).close()
        return local
    except OSError:
        base = os.environ.get("APPDATA") or Path.home() / ".config"
        user = Path(base) / "probeocr" / "layouts"
        user.mkdir(parents=True, exist_ok=True)
        return user


LAYOUTS = pick_layouts_dir()
BINARY = ROOT / "bin" / ("probeocr.exe" if os.name == "nt" else "probeocr")
TESSDATA = ROOT / "tessdata"   # bundled model; absent in a dev checkout
IMAGE_EXTS = {".png", ".jpg", ".jpeg", ".bmp", ".tif", ".tiff", ".gif", ".webp"}
MIME = {".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg",
        ".bmp": "image/bmp", ".tif": "image/tiff", ".tiff": "image/tiff",
        ".gif": "image/gif", ".webp": "image/webp"}
SKIP_DIRS = {"node_modules", "__pycache__", "venv", ".venv", "site-packages", "CMakeFiles"}
TREE_MAX_DEPTH = 8
TREE_MAX_IMAGES = 5000
DEFAULT_ROOT = Path.cwd()


def natural_key(p: Path):
    return [int(t) if t.isdigit() else t.lower() for t in re.split(r"(\d+)", p.name)]


def image_tree(root: Path):
    """Nested {name, path, dirs, images} for every folder under root that holds images."""
    count = 0
    truncated = False

    def walk(d: Path, depth: int):
        nonlocal count, truncated
        try:
            entries = sorted(d.iterdir(), key=natural_key)
        except OSError:
            return None
        dirs, images = [], []
        for e in entries:
            if e.name.startswith("."):
                continue
            if e.is_dir() and not e.is_symlink():
                if e.name in SKIP_DIRS or depth >= TREE_MAX_DEPTH:
                    continue
                sub = walk(e, depth + 1)
                if sub:
                    dirs.append(sub)
            elif e.suffix.lower() in IMAGE_EXTS and e.is_file():
                if count >= TREE_MAX_IMAGES:
                    truncated = True
                    continue
                images.append(str(e.resolve()))
                count += 1
        if not dirs and not images and depth > 0:
            return None
        return {"name": d.name, "path": str(d.resolve()), "dirs": dirs, "images": images}

    tree = walk(root, 0)
    return tree, count, truncated


def safe_layout_name(name: str) -> str:
    name = re.sub(r"[^A-Za-z0-9 _.-]", "", name).strip().strip(".")
    if not name:
        raise ValueError("layout name is empty")
    return name


def layout_to_text(layout: dict) -> str:
    """Convert the frontend's JSON layout to the C program's line format."""
    one_line = lambda s: " ".join(str(s).split())
    lines = ["# generated by probeocr frontend"]
    anchor = layout.get("anchor")
    if anchor:
        lines.append(f"ref {layout['ref']}")
        lines.append("anchor {x} {y} {w} {h} {search}".format(
            **{k: int(round(anchor[k])) for k in ("x", "y", "w", "h", "search")}))
    for i, p in enumerate(layout["probes"]):
        mode = "text" if p.get("mode") == "text" else "num"
        label = one_line(p.get("label") or f"probe{i + 1}")
        x, y, w, h = (int(round(p[k])) for k in ("x", "y", "w", "h"))
        lines.append(f"probe {x} {y} {w} {h} {mode} {label}")
    return "\n".join(lines) + "\n"


class Handler(BaseHTTPRequestHandler):
    def log_message(self, fmt, *args):
        pass

    # -- helpers -----------------------------------------------------
    def send_json(self, obj, status=200):
        body = json.dumps(obj).encode()
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def send_error_json(self, msg, status=400):
        self.send_json({"error": msg}, status)

    def read_json(self):
        n = int(self.headers.get("Content-Length", 0))
        return json.loads(self.rfile.read(n) or b"{}")

    # -- routes ------------------------------------------------------
    def do_GET(self):
        url = urlparse(self.path)
        q = {k: v[0] for k, v in parse_qs(url.query).items()}
        try:
            if url.path == "/":
                body = (STATIC / "index.html").read_bytes()
                self.send_response(200)
                self.send_header("Content-Type", "text/html; charset=utf-8")
                self.send_header("Content-Length", str(len(body)))
                self.end_headers()
                self.wfile.write(body)
            elif url.path == "/api/tree":
                d = Path(q.get("root") or DEFAULT_ROOT).expanduser().resolve()
                if not d.is_dir():
                    return self.send_error_json(f"not a folder: {d}")
                tree, count, truncated = image_tree(d)
                self.send_json({"root": str(d.resolve()), "tree": tree,
                                "count": count, "truncated": truncated})
            elif url.path == "/api/image":
                p = Path(q.get("path", ""))
                if p.suffix.lower() not in IMAGE_EXTS or not p.is_file():
                    return self.send_error_json("not an image", 404)
                body = p.read_bytes()
                self.send_response(200)
                self.send_header("Content-Type", MIME.get(p.suffix.lower(), "application/octet-stream"))
                self.send_header("Content-Length", str(len(body)))
                self.send_header("Cache-Control", "max-age=60")
                self.end_headers()
                self.wfile.write(body)
            elif url.path == "/api/layouts":
                self.send_json({"layouts": sorted(p.stem for p in LAYOUTS.glob("*.json"))})
            elif url.path == "/api/layout":
                p = LAYOUTS / f"{safe_layout_name(q.get('name', ''))}.json"
                if not p.is_file():
                    return self.send_error_json("no such layout", 404)
                self.send_json(json.loads(p.read_text(encoding="utf-8")))
            else:
                self.send_error_json("not found", 404)
        except (ValueError, OSError) as e:
            self.send_error_json(str(e))

    def do_POST(self):
        url = urlparse(self.path)
        try:
            if url.path == "/api/layout":
                data = self.read_json()
                name = safe_layout_name(data.get("name", ""))
                (LAYOUTS / f"{name}.json").write_text(json.dumps(data["layout"], indent=2),
                                                      encoding="utf-8")
                self.send_json({"saved": name})
            elif url.path == "/api/run":
                self.run_extraction(self.read_json())
            else:
                self.send_error_json("not found", 404)
        except (ValueError, KeyError, OSError) as e:
            self.send_error_json(str(e))

    def run_extraction(self, data):
        if not BINARY.exists():
            return self.send_error_json(
                f"{BINARY} not found. Build it first with `make` in {ROOT}.", 500)
        layout, images = data["layout"], data["images"]
        if not layout.get("probes"):
            return self.send_error_json("draw at least one probe box first")

        with tempfile.NamedTemporaryFile("w", suffix=".txt", delete=False,
                                         encoding="utf-8") as f:
            f.write(layout_to_text(layout))
            layout_path = f.name

        cmd = [str(BINARY)]
        if TESSDATA.is_dir():
            cmd += ["--tessdata", str(TESSDATA)]
        # The C side speaks UTF-8 regardless of platform (Windows defaults to cp1252).
        proc = subprocess.Popen(cmd + [layout_path, "-"],
                                stdin=subprocess.PIPE, stdout=subprocess.PIPE,
                                stderr=subprocess.PIPE, encoding="utf-8",
                                errors="replace", bufsize=1)
        # Feed paths and drain stderr on threads so no pipe can fill up and deadlock.
        def feed():
            for img in images:
                proc.stdin.write(img + "\n")
            proc.stdin.close()
        errs = []
        threading.Thread(target=feed, daemon=True).start()
        err_t = threading.Thread(target=lambda: errs.append(proc.stderr.read()), daemon=True)
        err_t.start()

        self.send_response(200)
        self.send_header("Content-Type", "application/x-ndjson")
        self.end_headers()
        try:
            for line in proc.stdout:
                self.wfile.write(line.encode())
                self.wfile.flush()
            proc.wait()
            err_t.join(timeout=2)
            if proc.returncode != 0:
                msg = (errs[0] if errs else "").strip() or f"exit code {proc.returncode}"
                self.wfile.write((json.dumps({"fatal": msg}) + "\n").encode())
        except (BrokenPipeError, ConnectionResetError):
            proc.kill()  # browser went away; stop the batch
        finally:
            Path(layout_path).unlink(missing_ok=True)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--port", type=int, default=8765)
    ap.add_argument("--no-browser", action="store_true")
    ap.add_argument("--root", default=".",
                    help="folder whose image tree is shown (default: current directory)")
    args = ap.parse_args()
    global DEFAULT_ROOT
    DEFAULT_ROOT = Path(args.root).expanduser().resolve()

    if not BINARY.exists():
        print(f"warning: {BINARY} is missing; run `make` in {ROOT}", file=sys.stderr)
    srv = ThreadingHTTPServer(("127.0.0.1", args.port), Handler)
    url = f"http://127.0.0.1:{args.port}/"
    print(f"probeocr frontend at {url}  (Ctrl-C to stop)")
    print(f"layouts saved in {LAYOUTS}")
    if not args.no_browser:
        threading.Timer(0.5, webbrowser.open, [url]).start()
    try:
        srv.serve_forever()
    except KeyboardInterrupt:
        pass


if __name__ == "__main__":
    main()
